EtcdConnectString: 127.0.0.1:2379 #etcd连接地址 如果是连接多个地址，请用;分割
EtcdNameSpace: YaIce_Service     #命名空间
PortStart: 10001             #网络端口开始
PortEnd: 10100             #网络端口结束
HttpPort: 8888              #http网络接口
ClusterName: YaIce             #用于Etcd存储key
IntranetHost: 10.0.0.10     #内网地址
ExtranetHost: 10.0.0.10     #外网地址
IntranetPingService: 2000         #单位ms 内网服务内部Ping
ExtranetPingService: 5000         #单位ms 外网服务内部Ping
MaxConnectNumber: 5000            #网络最大连接数
ExcelFilePath: #excel文件路径
ConfigFilePath: ./yaice/resource/server_config.yaml #资源文件
LogFilePath: #日志文件